### PR TITLE
feat: add chore type commit

### PR DESCRIPTION
**Pull request by eavam**
Add commit type "chore". It needed for editing scripts or other not production files.

### CODE REVIEW

**Comment by nitayneeman** [comment]
Hey @eavam,
Thanks for your PR!

The "chore" type was removed on purpose, and actually was replaced with "build", in order to be aligned with the Angular commit message [conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type).

But you can always customize your types 🙂

**Comment by eavam** [comment]
> Hey @eavam,
> Thanks for your PR!
> 
> The "chore" type was removed on purpose, and actually was replaced with "build", in order to be aligned with the Angular commit message [conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type).
> 
> But you can always [customize](https://github.com/nitayneeman/vscode-git-semantic-commit#customize-your-types) your types 🙂

Wow, thanks :) Maybe it's worth adding a link then, so that it is clear why these messages are selected?
I can add if necessary :)

**Comment by nitayneeman** [comment]
> > Hey @eavam,
> > Thanks for your PR!
> > The "chore" type was removed on purpose, and actually was replaced with "build", in order to be aligned with the Angular commit message [conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type).
> > But you can always [customize](https://github.com/nitayneeman/vscode-git-semantic-commit#customize-your-types) your types 🙂
> 
> Wow, thanks :) Maybe it's worth adding a link then, so that it is clear why these messages are selected?
> I can add if necessary :)

Great idea - I think we can also add a short sentence under the preview image that mentions it, like: 
"Notice that the default types are aligned with the Angular commit message conventions."

And, the word "conventions" will link to them.

Go for it if you can :)

**Comment by eavam** [comment]
I'm added message in #16 😁

**Comment by nitayneeman** [comment]
> I'm added message in #16 😁

LOL, I missed out your recent comment and merged this PR by mistake (but reverted it) 😅

Anyway, thank you!

**Pull request merged**
